### ISSUE TITLE
cycle-themes issue

### ISSUE THREAD

**Issue by littlestone** [larstvei/dot-emacs#1]
Hi Lars,

Thanks for sharing your dot-emacs configurations, I like it so much! :)

I am currently running 64 bit Emacs v24.5 on windows, I've encountered a little issue for the cycle-themes function located in the Visual section, it just doesn't show up in the Emacs Commands list (M-x) even though I have tried to evaluate it manually. Am I doing something wrong?

Thanks to advise!
Junjie Tang

**Comment by larstvei** [comment]
Hi!

I'm glad you like it!

The `cycle-themes` is implemented using a closure, meaning that the state is encapsulated inside the function. So  `cycle-themes` does not actually change the theme (so it should perhaps be renamed), but returns a function that can cycle themes.

I never call it using `M-x`, because I've got it bound to a key:

``` emacs-lisp
(define-key custom-bindings-map (kbd "C-c .") (cycle-themes))
```

Notice the parenthesis around `cycle-themes`; this way we bind the function _that is returned_ to a key. I'm not really sure how one could make this callable through `M-x` without changing the definition of `cycle-themes`.

Here is what you could do to make it callable (which does change the definition of `cycle-themes`):

``` emacs-lisp
(defvar my-themes '#1=(leuven monokai . #1#))

(defun cycle-themes ()
  "A function that lets you cycle your themes."
  (interactive)
  ;; Rotates the thme cycle and changes the current theme.
  (load-theme (car (setq my-themes (cdr my-themes))) t))
```

The reason I prefer the former is that there is less global state, and it was more fun to implement.

- Lars

**Comment by littlestone** [comment]
Hi Lars,

Thanks for the quick answer, it's well explained and crystal clear! :)

Best regards,
Junjie
