### ISSUE TITLE
error when loaded

### ISSUE THREAD

**Issue by eitazhou** [larstvei/dot-emacs#3]
I backed up my old .emacs.d dir ,and  copy all files to .emacs.d dir, When I start a new compiled emacs(25.1) in Mac os,  It shows error:
Warning (initialization): An error occurred while loading ‘~/.emacs.d/init.el’:
error: Recursive load, ~/.emacs.d/init.el, ~/.emacs.d/init.el ...

**Comment by larstvei** [comment]
I just tried on my machine (a mac), with Emacs 25 and everything went fine.

On first run the `init.el` should run `org-tangle` to generate (and replace) the `init.el` file from `init.org`, and then load (the newly replaced) `init.el`.

What seems to have happened to you is that for some reason the `org-tangle` step didn't work, but it didn't cause an error, which allows the init-file to load itself recursively.

This would happen if your `.emacs.d` don't contain the org-file!

You probably wan't to clone the repo, and rename the repo to `.emacs.d`, instead of moving the files. That way you preserve the version control.
